### PR TITLE
Bower & Typings Support

### PR DESCRIPTION
**Pull request by jpsfs**
Hi!

This PR aims to update the bower.json version number and include the typings definition on the package.json.

### CODE REVIEW

**Comment by jpsfs** [comment]
Fixes #153

**Comment by sharikovvladislav** [comment]
This is because of that: https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

**Comment by kristate** [comment]
Thank-you for your Patch!

We have forked the project and are accepting Pull Requests here:
https://github.com/NeraiCorp/getUserBarcode

**Comment by TomasHubelbauer** [comment]
The version has since this PR changed to `12.0.1`, but we will fix that with a new PR.

**Comment by ericblade** [comment]
LGTM, but i think it'll merge conflict with the bower version change, so rebase will be needed.

**Pull request merged**
