### PR TITLE
inputStream.area to allow px values

### PR DESCRIPTION
**Pull request by JauernigIT**
So far, the `inputStream.area` config definition allowed only `%` values, because `CVUtils._parseCSSDimensionValues` and `CVUtils._dimensionsConverters` only allowed percentages. I've adapted it to work with full (px) values as well.

### CODE REVIEW

**Comment by serratus** [comment]
Thanks for this addition. Using `px` values for `inputStream.area` is a little bit tricky, because they are dependent on the physical resolution of the input image. Can you explain to me the scenario in which you would use `px` instead of `%` ? I opted for `%` because, when changing the camera-resolution, the area doesn't need to be adapted.

**Comment by JauernigIT** [comment]
Ok, I see your point. So here is my scenario: I have the requirement that the video is shown in a quadratic or landscape format. But on mobile devices, even if I set width=640 and height=480, the video is shown in portrait mode, when the phone is held in portrait. To fulfill my requirement, I have to crop the viewport around the video with CSS and then I have to set the Quagga config area top/border to not evaluate the area that is hidden on the viewport.

**Comment by serratus** [comment]
Well, that's an interesting point you make here. Chrome understands a constraint `aspectRatio` which would help in this scenario. However, this does not work in Edge nor Firefox.
I'm interested in how you handle the transition from portrait to landscape and back? Do you change the configuration on the fly, or do you always operate on a quadratic format?
Anyways, do you still think defining the `inputStream.area` in `px` values is necessary? If so, could you please resolve the conflicts?

**Comment by JauernigIT** [comment]
In my case, I'm not handling landscape mode, thus I'm skipping the transition from/to portrait. And yes, I still need the definition of px values (for browsers other than Chrome). I think, it's a valuable addition for the `area` config, so I will update the code...

**Comment by maxttien-22** [comment]
excuse me, i have a issue with quagga.js
quagga  working for this image:


but not working for this image


and it's working for this image:

but not working when i change image size:

i don't understand ?
please help me

**Pull request closed without merging**
