### PR TITLE
Update typings to match v0.12.1

### PR DESCRIPTION
**Pull request by danmana**
Updates:
* added `CameraAccess`
* added `frequency`
* added `decoder.multiple`
* updated `decoder.readers` to support supplements configuration
* reference the typings file in package.json

### CODE REVIEW

**Comment by sheam** [comment]
Any chance this gets merged?

**Comment by kristate** [comment]
Thank-you for your Patch!

We have forked the project and are accepting Pull Requests here:
https://github.com/NeraiCorp/getUserBarcode

**Comment by ericblade** [comment]
sorry, i didn't notice when this came into my inbox earlier.. looks good to me, so i went ahead with it.

**Comment by nwinger** [comment]
@ericblade How can I use this with a Typescript project at all? Cannot find the typings from the project when doing an import.

`import quagga from "Quagga";`

VSCode reports: 

> "Could not find a declaration file for module 'quagga'. '...(removed for brevity)/node_modules/quagga/lib/quagga.js' implicitly has an 'any' type.\n  Try `npm install @types/quagga` if it exists or add a new declaration (.d.ts) file containing `declare module 'quagga';`"
}

**Comment by ericblade** [comment]
@TomasHubelbauer ? I have no experience with Typescript, but Tomas does.

are you using a checkout from git, or the npm installed module? I don't believe we have access to update the npm module, still working that out @serratus ?

**Comment by nwinger** [comment]
> @TomasHubelbauer ? I have no experience with Typescript, but Tomas does.
> 
> are you using a checkout from git, or the npm installed module? I don't believe we have access to update the npm module, still working that out @serratus ?

I'm using npm install. Would be nice to have it work with its own typings, or simply install them via @types/quagga like many of the other packages do :)

**Comment by ericblade** [comment]
OK, so, @serratus , the original author, has bowed out for a while.  @TomasHubelbauer and I have volunteered to keep up with maintenance, as users of the project, and devs, but I don't think either of us are particularly well versed in particularly relevant topics.  I'm not sure if anyone other than @serratus can update npm at this time.   In the meantime, I'm pretty dedicated to keeping up with any pull reqs, and trying to address bug reports and questions as best I can.

SO.. any info on how to add @types/quagga would be beneficial to me, and I can see if I can handle that.  In the meantime, the last npm release does not having the types file, so I think you can clone it from the repo, and use it from there? i'm not sure, like I said, I don't have any experience with Typescript, at the moment . . so guidance is helpful :)

**Comment by nwinger** [comment]
@ericblade I'm pretty swamped with work and being a dad at the dad at the momen 😆 🚀 
However, the DefinitelyTyped repo offers some good guidance here: [https://github.com/DefinitelyTyped/DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped)

I think I saw that you actually provide a typings file with your project - not sure how up to date it is though.

**Comment by TomasHubelbauer** [comment]
Yeah the problem is the typings are not released and neither me nor Eric can rerelease unfortunately. To the comment saying they would prefer `@types/quagga`, I'd actually recommend otherwise, to instead stick with `types` in `package.json` as the former is mostly a bridge for packages that have not adopted TypeScript and we're looking to advertise a commitment to providing first party typings with the vetting and responsibility of keeping them up to date that comes from them being first party.

Unfortunately, and I'm echoing Eric here once more, neither of us have particular experience with the core of this library, I personally don't at all nor do I think with the time I can dedicate for this project will I be able to gain it. I'm basically just trying to help keep this project alive the best way I can as it was very useful for me in the past and I'm grateful to @serratus for putting it together.

Right now, before we get release rights, I'd recommend you point your package.json at `master` GitHub URL and roll with that.

Congrats on your kid as well! Enjoy the ride 😁

**Pull request merged**
